import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WS
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Un = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Ps = new javax.swing.JLabel();
        Ps2 = new javax.swing.JLabel();
        Fn = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        Ln = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        Showpass = new javax.swing.JRadioButton();
        Adrs = new javax.swing.JLabel();
        Lastname = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        Gd = new javax.swing.JLabel();
        Sks = new javax.swing.JLabel();
        Pg = new javax.swing.JCheckBox();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Vg = new javax.swing.JCheckBox();
        Sb = new javax.swing.JCheckBox();
        Tl = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("REGISTRATION");

        Un.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Un.setForeground(new java.awt.Color(255, 102, 0));
        Un.setText("Username");

        Ps.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ps.setForeground(new java.awt.Color(255, 102, 0));
        Ps.setText("Password");

        Ps2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ps2.setForeground(new java.awt.Color(255, 102, 0));
        Ps2.setText("Confirm Password");

        Fn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fn.setForeground(new java.awt.Color(255, 102, 0));
        Fn.setText("First name:");

        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });

        Ln.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ln.setForeground(new java.awt.Color(255, 102, 0));
        Ln.setText("Last name:");

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        Showpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Showpass.setForeground(new java.awt.Color(255, 102, 0));
        Showpass.setText("Show");
        Showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowpassActionPerformed(evt);
            }
        });

        Adrs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Adrs.setForeground(new java.awt.Color(255, 102, 0));
        Adrs.setText("Address:");

        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        Gd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gd.setForeground(new java.awt.Color(255, 102, 0));
        Gd.setText("Gender:");

        Sks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sks.setForeground(new java.awt.Color(255, 102, 0));
        Sks.setText("Skills:");

        Pg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pg.setForeground(new java.awt.Color(255, 102, 0));
        Pg.setText("Programming");
        Pg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PgActionPerformed(evt);
            }
        });

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 102, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("FORM");

        Vg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Vg.setForeground(new java.awt.Color(255, 102, 0));
        Vg.setText("Visual Graphics");

        Sb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sb.setForeground(new java.awt.Color(255, 102, 0));
        Sb.setText("Shat kay Bagsak");

        Tl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tl.setForeground(new java.awt.Color(255, 102, 0));
        Tl.setText("Team lead");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Specialization:");

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton2.setText("Java");

        jRadioButton3.setForeground(new java.awt.Color(255, 102, 0));
        jRadioButton3.setText("Python");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Have an account already?");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Log in");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fn)
                            .addComponent(Ps2)
                            .addComponent(Ln)
                            .addComponent(Adrs)
                            .addComponent(Gd)
                            .addComponent(Sks)
                            .addComponent(Ps)
                            .addComponent(Un)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Pg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Vg))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Firstname)
                                        .addComponent(Address)
                                        .addComponent(Lastname)
                                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Showpass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Sb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(33, 33, 33)
                                .addComponent(jRadioButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Un)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps)
                    .addComponent(Showpass)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps2)
                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fn)
                    .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ln)
                    .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adrs)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sks)
                    .addComponent(Pg)
                    .addComponent(Vg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sb)
                    .addComponent(Tl))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel11)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Un = Username.getText();
        String Ps = Password.getText();
        String Ps2 = ConfirmPassword.getText();
        String Fs = Firstname.getText();
        String Ls = Lastname.getText();
        String Adrs = Address.getText();
                
                
    if (Un.isEmpty() || Ps.isEmpty() || Ps2.isEmpty() || Fs.isEmpty()) {
        Username.setBackground(Color.RED);
        Password.setBackground(Color.RED);
        ConfirmPassword.setBackground(Color.RED);
        Firstname.setBackground(Color.RED);
        Lastname.setBackground(Color.RED);
        Address.setBackground(Color.RED);
        System.out.println("Please fill in all fields.");
        return;
    }
    
    if (!isValidString(Un)) {
        Username.setBackground(Color.RED);
        System.out.println("Enter valid fullname.");
        return;
        }

       if (!Ps.equals(Ps2)) {
        
        ConfirmPassword.setBackground(Color.RED); 
        System.out.println("Passwords do not match. Please try again.");
        return;
    }

    if (!isValidEmail(Fs)) {
        Firstname.setBackground(Color.RED);
        System.out.println("Invalid email format. Please enter a valid email.");
        return;
    }
    
        String course = (String) GenderComboBox.getSelectedItem();
    if (course.equals("Gender")) {
        System.out.println("Please select a course.");
        return;
    }
    
    String Gender = "";
    if (Male.isSelected()) {
        Gender = "Male";
    } else if (Female.isSelected()) {
        Gender = "Female";
    } else {
        System.out.println("Please select a gender.");
        return;
    }

    String Skills = "";
    if (Pg.isSelected()) {
        Skills += "Programming, ";
    }
    if (Vg.isSelected()) {
        Skills += "Visual Graphics, ";
    }
    if (Sb.isSelected()) {
        Skills += "Shat kay Bagsak, ";
    }
    if (Tl.isSelected()) {
        Skills += "Team lead, ";
    }
   
    

    String directoryPath = "C:\\Users\\USER\\Documents\\form";
    new java.io.File(directoryPath).mkdirs();

    String filePath = directoryPath + "\\" + Un + ".txt";
    
    if (new java.io.File(filePath).exists()) {
        Username.setBackground(Color.RED);
        System.out.println("Email already exists, please use a new one.");
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
        writer.write("Username: " + Un);
        writer.newLine();
        writer.write("Password: " + Ps);
        writer.newLine();
        writer.write("ConfirmPassword: " + Ps2);
        writer.newLine();
        writer.write("Firstname: " + Fs);
        writer.newLine();
        writer.write("Lastname: " + Ls);
        writer.newLine();
        writer.write("Address: " + Adrs);
        writer.newLine();
        writer.write("Gender: " + Gd);
        writer.newLine();
         writer.write("Skills: " + Sks);
        writer.newLine();
        System.out.println("Account created successfully!");

        Username.setBackground(null);
        Password.setBackground(null);
        ConfirmPassword.setBackground(null);
        Firstname.setBackground(null);
        Lastname.setBackground(null);
        Address.setBackground(null);
    
    } catch (IOException e) {
        e.printStackTrace();
     }
        LogIN login = new LogIN();
        login.setVisible(true);
        login.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void ShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowpassActionPerformed
       if(showpass.isSelected()){
            Ps.setEcho((char) 0);
        }else{
            Ps2.setEchoChar('*');
        }  // TODO add your handling code here:
    }//GEN-LAST:event_ShowpassActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void PgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Adrs;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Firstname;
    private javax.swing.JLabel Fn;
    private javax.swing.JLabel Gd;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Lastname;
    private javax.swing.JLabel Ln;
    private javax.swing.JPasswordField Password;
    private javax.swing.JCheckBox Pg;
    private javax.swing.JLabel Ps;
    private javax.swing.JLabel Ps2;
    private javax.swing.JCheckBox Sb;
    private javax.swing.JRadioButton Showpass;
    private javax.swing.JLabel Sks;
    private javax.swing.JCheckBox Tl;
    private javax.swing.JLabel Un;
    private javax.swing.JTextField Username;
    private javax.swing.JCheckBox Vg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
